### ISSUE TITLE
Prepare for v1.0 Release

### ISSUE THREAD

**Issue by arnavs** [QuantEcon/lecture-source-jl#191]
Currently, we have a lot of open issues with varying importance levels and timeframes. There's also a lot of different people working on them. So I think it would be good to create this meta-issue to organize all the moving parts. 

The goal with these changes is to get a (necessarily imperfect) v1.0 release of the lectures that we feel comfortable presenting in 1-2 weeks. 

### Plots 

- [ ] Issue https://github.com/QuantEcon/lecture-source-jl/issues/189, about degraded 3D plots with GR. Assigned to @ajozefiak 
- [ ] Issue https://github.com/QuantEcon/lecture-source-jl/issues/188, about conflict between `Plots` and `StatPlots` when both are used inside the same lecture. Assigned to @arnavs. 

### Jupinx/rST
- [ ] Issue https://github.com/QuantEcon/lecture-source-jl/issues/185, about warnings thrown by Jupinx when generating index files. Assigned to TBD 
- [ ] Issue https://github.com/QuantEcon/lecture-source-jl/issues/183, about Jupinx objecting to title levels in a specific lecture. Assigned to TBD
- [ ] Issue https://github.com/QuantEcon/lecture-source-jl/issues/146 about adding exercise credits back. Assigned to @arnavs 

### Passes 
- [ ] Issue https://github.com/QuantEcon/lecture-source-jl/issues/133, about moving over any dot product of a PDF vector to an `Expectations.jl` object. Assigned to @yolsever. Also includes replacing `do_quad` with `FastGaussQuadrature`. 
- [ ] Issue https://github.com/QuantEcon/lecture-source-jl/issues/134, about replacing QuantEcon fixed point routines like `compute_fixed_point`. Assigned to @XiaojunGuan. 
- [ ] Issue https://github.com/QuantEcon/lecture-source-jl/issues/135, about replacing `struct`s in the lectures with `NamedTuple`s. Assigned to @Nosferican, @arnavs and potentially @ajozefiak. 
- [ ] Issue https://github.com/QuantEcon/lecture-source-jl/issues/146, about standardizing interpolation on `Interpolations.jl` Assigned to @arnavs and @ajozefiak. 

### Rewrites 

- [ ] Need to go through every lecture, enforce the style guide, etc. This is ongoing work by @arnavs and @Nosferican.

**Comment by Nosferican** [comment]
There is also the issue with the sphinxcontrib-jupyter rendering of LaTeX.

**Comment by arnavs** [comment]
I think @natashawatkins alerted Matt about that. In general, let's handle issues with Jupinx proper by just filing an issue on their repo. Don't think any of us are capable of filing those patches by ourselves.
