### ISSUE TITLE
Global Regression Test Tracker

### ISSUE THREAD

**Issue by arnavs** [QuantEcon/lecture-source-jl#41]
For a given lecture, in between the undeprecation and the rewriting/refactoring, we want to insert regression tests to ensure that the output does not change. 

# Guidelines

Some thoughts, based on discussions with @jlperla:

- When testing arrays, try not to test the bounds, but rather some arbitrary interior value. 
- In general, try to test values that depend on many other values, since it's unlikely that errors in those components will exactly cancel. Something like a checksum. 
- ~~We should put these tests in their own blocks with a special comment (`# jl-test`, I believe), so that we can later efficiently delete all blocks that contain that comment.~~ See README for this now. 
- ~~For plots, the testing procedure is still TBD. Perhaps we can eyeball it, or maybe serialize the plot object and save it. Not sure what a good approach is here.~~ See Jesse's comment below for how to handle this. 

# Tracker

## Programming in Julia 
- [ ] [Setting up your Julia Environment](https://lectures.quantecon.org/jl/getting_started.html)
- [ ] [An Introductory Example](https://lectures.quantecon.org/jl/julia_by_example.html)
- [ ] [Julia Essentials](https://lectures.quantecon.org/jl/julia_essentials.html)
- [ ] [Vectors, Arrays, and Matrices](https://lectures.quantecon.org/jl/julia_arrays.html)
- [ ] [Types, Methods, and Dispatch](https://lectures.quantecon.org/jl/types_methods.html)
- [ ] [The Need for Speed](https://lectures.quantecon.org/jl/need_for_speed.html)
- [ ] [Plotting in Julia](https://lectures.quantecon.org/jl/julia_plots.html)
- [ ] [Useful Libraries](https://lectures.quantecon.org/jl/julia_libraries.html)

## Tools and Techniques 
- [x] [Linear Algebra](https://lectures.quantecon.org/jl/linear_algebra.html)
- [x] [Orthogonal Projections and their Applications](https://lectures.quantecon.org/jl/orth_proj.html) (#46)
- [x] [LLN and CLT](https://lectures.quantecon.org/jl/lln_clt.html) (#47)
- [x] [Linear State-Space Models](https://lectures.quantecon.org/jl/linear_models.html) (#48)
- [x] [Finite Markov Chains](https://lectures.quantecon.org/jl/finite_markov.html) (#49)
- [x] [Continuous State Markov Chains](https://lectures.quantecon.org/jl/stationary_densities.html) (#50)
- [x] [A First Look at the Kalman Filter](https://lectures.quantecon.org/jl/kalman.html) (#51)

## Dynamic Programming 
- [ ] [Shortest Paths](https://lectures.quantecon.org/jl/short_path.html)
- [x] [Job Search I: The McCall Search Model](https://lectures.quantecon.org/jl/mccall_model.html) (#55)
- [x] [Job Search II: Search and Separation](https://lectures.quantecon.org/jl/mccall_model_with_separation.html) (#56)
- [x] [A Problem that Stumped Milton Friedman](https://lectures.quantecon.org/jl/wald_friedman.html) (#57)
- [x] [Job Search III: Search with Learning](https://lectures.quantecon.org/jl/odu.html) (#61)
- [x] [Job Search IV: Modeling Career Choice](https://lectures.quantecon.org/jl/career.html) (#63)
- [x] [Job Search V: On-the-Job Search](https://lectures.quantecon.org/jl/jv.html) (#64)
- [x] [Optimal Growth I: The Stochastic Optimal Growth Model](https://lectures.quantecon.org/jl/optgrowth.html) (#65)
- [x] [Optimal Growth II: Time Iteration](https://lectures.quantecon.org/jl/coleman_policy_iter.html) (#66)
- [x] [Optimal Growth III: The Endogenous Grid Method](https://lectures.quantecon.org/jl/egm_policy_iter.html) (#68)
- [x] [LQ Dynamic Programming Problems](https://lectures.quantecon.org/jl/lqcontrol.html) (#69)
- [x] [Optimal Savings I: The Permanent Income Model](https://lectures.quantecon.org/jl/perm_income.html) (#71)
- [x] [Optimal Savings II: LQ Techniques](https://lectures.quantecon.org/jl/perm_income_cons.html) (#72)
- [x] [Consumption and Tax Smoothing with Complete and Incomplete Markets](https://lectures.quantecon.org/jl/smoothing.html) (#73)
- [x] [Optimal Savings III: Occasionally Binding Constraints](https://lectures.quantecon.org/jl/ifp.html) (#75)
- [x] [Robustness](https://lectures.quantecon.org/jl/robustness.html)
- [x] [Discrete State Dynamic Programming](https://lectures.quantecon.org/jl/discrete_dp.html)

## Multiple Agent Models
- [x] [Schelling's Segregation Model](https://lectures.quantecon.org/jl/schelling.html)
- [x] [A Lake Model of Employment and Unemployment](https://lectures.quantecon.org/jl/lake_model.html) (#79)
- [x] [Rational Expectations Equilibrium](https://lectures.quantecon.org/jl/rational_expectations.html)
- [x] [Markov Perfect Equilibrium](https://lectures.quantecon.org/jl/markov_perf.html)  (#105)
- [x] [Asset Pricing I: Finite State Models](https://lectures.quantecon.org/jl/markov_asset.html) (#106)
- [x] [Asset Pricing II: The Lucas Asset Pricing Model](https://lectures.quantecon.org/jl/lucas_model.html) (#107)
- [x] [Asset Pricing III: Incomplete Markets](https://lectures.quantecon.org/jl/harrison_kreps.html) (#108)
- [x] [Uncertainty Traps](https://lectures.quantecon.org/jl/uncertainty_traps.html) (#82)
- [x] [The Aiyagari Model](https://lectures.quantecon.org/jl/aiyagari.html) (#83)
- [x] [Default Risk and Income Fluctuations](https://lectures.quantecon.org/jl/arellano.html) (#109)
- [x] [Globalization and Cycles](https://lectures.quantecon.org/jl/matsuyama.html) (#110)

## Time Series Models
- [x] [Covariance Stationary Processes](https://lectures.quantecon.org/jl/arma.html) (#101)
- [x] [Estimation of Spectra](https://lectures.quantecon.org/jl/estspec.html) (#111)
- [x] [Additive Functionals](https://lectures.quantecon.org/jl/additive_functionals.html) (#112)
- [x] [Multiplicative Functionals](https://lectures.quantecon.org/jl/multiplicative_functionals.html) (#113)
- [x] [Classical Control with Linear Algebra](https://lectures.quantecon.org/jl/lu_tricks.html) (#114)
- [x] [Classical Filtering with Linear Algebra](https://lectures.quantecon.org/jl/classical_filtering.html) (#115)

## Dynamic Programming Squared
- [x] [Dynamic Stackelberg Problems](https://lectures.quantecon.org/jl/dyn_stack.html) (#116)
- [x] [Optimal Taxation in an LQ Economy](https://lectures.quantecon.org/jl/lqramsey.html) (#117)
- [x] [Optimal Taxation with State-Contingent Debt](https://lectures.quantecon.org/jl/opt_tax_recur.html) (#118)
- [ ] [Optimal Taxation without State-Contingent Debt](https://lectures.quantecon.org/jl/amss.html)

**Comment by jlperla** [comment]
> For plots, the testing procedure is still TBD. Perhaps we can eyeball it, or maybe serialize the plot object and save it. Not sure what a good approach is here.

Just pick some random points to verify the values of in the underlying data used by the plots.

**Comment by jlperla** [comment]
`random` was a poor choice of words.  I mean arbitrary but consistent between runs.

**Comment by jlperla** [comment]
The approach for now:
- At the top of every file, put in the block
```
.. code-block:: julia
    :class: test

    using Test

```

- Then, wherever you want to add in a test of things, use a simple julia test.   For example
```
.. code-block:: julia

    x = true

.. code-block:: julia
    :class: test

   @testset "x tests" begin
       @test x == true
       @test 1 == 1
       @test 1 ≈ 0.999999999
    end
```
- Generally no need for comments or anything else, as the test failure gives lots of information. 
- You can group these all in a section near the bottom of the notebook if it doesn't overwrite variables as it goes down.  Otherwise, scatter them where you want and split up code blocks as you see fit.

**Comment by jlperla** [comment]
I **really** think we should be using the SoftGlobalScope, as built into and default in Jupyter now: https://github.com/JuliaLang/IJulia.jl/releases/tag/v1.10.0

Basically, this means we do nothing and never use `global` or `local` unless we really need them for something (at which point we reorganize the code so we don't :-)

Will it work direclty in the REPL without wrapping in a function?  Not unless the REPL implements it as well, but I suspect that is coming, as well as for Juno.

**Comment by jlperla** [comment]
You are right about the `let` block at the intermidate values.  It is only a partial solution because it will take time to explain to people why variables dissapear.  I am now worried it would cause a lot of confusion for users.

**Comment by arnavs** [comment]
Closing this, since we've finished this pass, modulo `amss` and the introductory lectures @jlperla is working on.
