### ISSUE TITLE
Global Undeprecation Tracker

### ISSUE THREAD

**Issue by arnavs** [QuantEcon/lecture-source-jl#5]
This goal is to get all the lectures to a state where they run in Julia 1.0. This is distinct from making the code more "Julian," clean, suitable for teaching, etc. 

## Deprecation Tracker

We can check off each lecture when complete. Currently, @nosferican and I have our notes in [this](https://docs.google.com/spreadsheets/d/1WD3HFbyNkEQJWOBkvVFjYRM1elGPExLptEoOuD-lYeA/edit?ts=5b71e794#gid=0) Google doc. 

## Programming in Julia 
- [ ] [Setting up your Julia Environment](https://lectures.quantecon.org/jl/getting_started.html) 
- [ ] [An Introductory Example](https://lectures.quantecon.org/jl/julia_by_example.html) (https://github.com/ubcecon/lecture-source-jl/pull/7)
- [ ] [Julia Essentials](https://lectures.quantecon.org/jl/julia_essentials.html) (https://github.com/ubcecon/lecture-source-jl/pull/8)
- [ ] [Vectors, Arrays, and Matrices](https://lectures.quantecon.org/jl/julia_arrays.html) (https://github.com/ubcecon/lecture-source-jl/pull/9)
- [ ] [Types, Methods, and Dispatch](https://lectures.quantecon.org/jl/types_methods.html) (https://github.com/ubcecon/lecture-source-jl/pull/10)
- [ ] [The Need for Speed](https://lectures.quantecon.org/jl/need_for_speed.html) (https://github.com/ubcecon/lecture-source-jl/pull/11)
- [ ] [Plotting in Julia](https://lectures.quantecon.org/jl/julia_plots.html)
- [ ] [Useful Libraries](https://lectures.quantecon.org/jl/julia_libraries.html) (https://github.com/ubcecon/lecture-source-jl/pull/12)

## Tools and Techniques 
- [ ] [Linear Algebra](https://lectures.quantecon.org/jl/linear_algebra.html) (https://github.com/ubcecon/lecture-source-jl/pull/13)
- [ ] [Orthogonal Projections and their Applications](https://lectures.quantecon.org/jl/orth_proj.html) (https://github.com/ubcecon/lecture-source-jl/pull/14)
- [ ] [LLN and CLT](https://lectures.quantecon.org/jl/lln_clt.html) (https://github.com/ubcecon/lecture-source-jl/pull/15)
- [ ] [Linear State-Space Models](https://lectures.quantecon.org/jl/linear_models.html) (https://github.com/ubcecon/lecture-source-jl/pull/16)
- [ ] [Finite Markov Chains](https://lectures.quantecon.org/jl/finite_markov.html) (https://github.com/ubcecon/lecture-source-jl/pull/17)
- [ ] [Continuous State Markov Chains](https://lectures.quantecon.org/jl/stationary_densities.html) (https://github.com/ubcecon/lecture-source-jl/pull/18)
- [ ] [A First Look at the Kalman Filter](https://lectures.quantecon.org/jl/kalman.html) (https://github.com/ubcecon/lecture-source-jl/pull/21)

## Dynamic Programming 
- [ ] [Shortest Paths](https://lectures.quantecon.org/jl/short_path.html) (https://github.com/ubcecon/lecture-source-jl/pull/22)
- [ ] [Job Search I: The McCall Search Model](https://lectures.quantecon.org/jl/mccall_model.html)
- [ ] [Job Search II: Search and Separation](https://lectures.quantecon.org/jl/mccall_model_with_separation.html)
- [ ] [A Problem that Stumped Milton Friedman](https://lectures.quantecon.org/jl/wald_friedman.html)
- [ ] [Job Search III: Search with Learning](https://lectures.quantecon.org/jl/odu.html)
- [ ] [Job Search IV: Modeling Career Choice](https://lectures.quantecon.org/jl/career.html)
- [ ] [Job Search V: On-the-Job Search](https://lectures.quantecon.org/jl/jv.html)
- [ ] [Optimal Growth I: The Stochastic Optimal Growth Model](https://lectures.quantecon.org/jl/optgrowth.html)
- [ ] [Optimal Growth II: Time Iteration](https://lectures.quantecon.org/jl/coleman_policy_iter.html)
- [ ] [Optimal Growth III: The Endogenous Grid Method](https://lectures.quantecon.org/jl/egm_policy_iter.html)
- [ ] [LQ Dynamic Programming Problems](https://lectures.quantecon.org/jl/lqcontrol.html)
- [ ] [Optimal Savings I: The Permanent Income Model](https://lectures.quantecon.org/jl/perm_income.html)
- [ ] [Optimal Savings II: LQ Techniques](https://lectures.quantecon.org/jl/perm_income_cons.html)
- [ ] [Consumption and Tax Smoothing with Complete and Incomplete Markets](https://lectures.quantecon.org/jl/smoothing.html)
- [ ] [Optimal Savings III: Occasionally Binding Constraints](https://lectures.quantecon.org/jl/ifp.html)
- [ ] [Robustness](https://lectures.quantecon.org/jl/robustness.html)
- [ ] [Discrete State Dynamic Programming](https://lectures.quantecon.org/jl/discrete_dp.html)

## Multiple Agent Models
- [ ] [Schelling's Segregation Model](https://lectures.quantecon.org/jl/schelling.html)
- [ ] [A Lake Model of Employment and Unemployment](https://lectures.quantecon.org/jl/lake_model.html)
- [ ] [Rational Expectations Equilibrium](https://lectures.quantecon.org/jl/rational_expectations.html)
- [ ] [Markov Perfect Equilibrium](https://lectures.quantecon.org/jl/markov_perf.html)
- [ ] [Asset Pricing I: Finite State Models](https://lectures.quantecon.org/jl/markov_asset.html)
- [ ] [Asset Pricing II: The Lucas Asset Pricing Model](https://lectures.quantecon.org/jl/lucas_model.html)
- [ ] [Asset Pricing III: Incomplete Markets](https://lectures.quantecon.org/jl/harrison_kreps.html)
- [ ] [Uncertainty Traps](https://lectures.quantecon.org/jl/uncertainty_traps.html)
- [ ] [The Aiyagari Model](https://lectures.quantecon.org/jl/aiyagari.html)
- [ ] [Default Risk and Income Fluctuations](https://lectures.quantecon.org/jl/arellano.html)
- [ ] [Globalization and Cycles](https://lectures.quantecon.org/jl/matsuyama.html)

## Time Series Models
- [ ] [Covariance Stationary Processes](https://lectures.quantecon.org/jl/arma.html)
- [ ] [Estimation of Spectra](https://lectures.quantecon.org/jl/estspec.html)
- [ ] [Additive Functionals](https://lectures.quantecon.org/jl/additive_functionals.html)
- [ ] [Multiplicative Functionals](https://lectures.quantecon.org/jl/multiplicative_functionals.html)
- [ ] [Classical Control with Linear Algebra](https://lectures.quantecon.org/jl/lu_tricks.html)
- [ ] [Classical Filtering with Linear Algebra](https://lectures.quantecon.org/jl/classical_filtering.html)

## Dynamic Programming Squared
- [ ] [Dynamic Stackelberg Problems](https://lectures.quantecon.org/jl/dyn_stack.html)
- [ ] [Optimal Taxation in an LQ Economy](https://lectures.quantecon.org/jl/lqramsey.html)
- [ ] [Optimal Taxation with State-Contingent Debt](https://lectures.quantecon.org/jl/opt_tax_recur.html)
- [ ] [Optimal Taxation without State-Contingent Debt](https://lectures.quantecon.org/jl/amss.html)

**Comment by arnavs** [comment]
Also some running guidelines, per @Nosferican:

```
- `Array{T}(dims...)` to `zeros` when possible or `similar` if suitable
- `begin` blocks for each non global
- Drop type annotation except for dispatch
- Promote flavored syntax `maximum(abs, -3:3)`
- Use `::AbstractMatrix{<:Number}'`
- Use `eachindex` if possible, if not `1:n`
- Use `using PkgA, PkgB, PkgC`
- Drop docstring
```
