### ISSUE TITLE
Test the Lectures Against Julia 1.1

### ISSUE THREAD

**Issue by arnavs** [QuantEcon/lecture-source-jl#528]
Per semver this is supposed to be backwards-compatible, so the transition shouldn't be too bad. 

Things that will need doing:

- [ ] Run the lectures again using the 1.1 IJulia kernel and make sure regression tests pass.  (#531)
- [ ] Take the time to remove unnecessary `Compat` includes 
- [ ] Make some edits for clarity, such as the `eachcol/eachrow` functions in 1.1
- [ ] Take the time to look at the `QELP`, `QELAP`, etc. and see if we need to make any changes.  (#532)
- [ ] Look at all the Docker images (`quantecon/base`, VSE syzygy, `jupinx`, `quanteconhub-docker`, etc.) and make sure that they are up to date.

cc @nosferican @jlperla

**Comment by jlperla** [comment]
Sounds great.
