### ISSUE TITLE
Global Style Tracker

### ISSUE THREAD

**Issue by arnavs** [QuantEcon/lecture-source-jl#6]
This is the counterpoint of #1, focused on making stylistic improvements to the lectures. As before, we can check off each lecture when we're satisfied with it. 

## General Fixes 

- [ ] Docstrings.
- [ ] Replacing default outer constructors with `@with_kw`. 
- [ ] Replacing homebrewed quadrature with `Expectations.jl`. 
- [ ] Replacing homebrewed iteration with `fixedpoint()`. 
- [ ] Eliminating repeatedly nested loops (like in the [career and job choice](https://lectures.quantecon.org/jl/career.html) lecture). 
- [ ] Settling on a consistent plot library (Plots/GR?).

## Programming in Julia 
- [ ] [Setting up your Julia Environment](https://lectures.quantecon.org/jl/getting_started.html)
- [ ] [An Introductory Example](https://lectures.quantecon.org/jl/julia_by_example.html)
- [ ] [Julia Essentials](https://lectures.quantecon.org/jl/julia_essentials.html)
- [ ] [Vectors, Arrays, and Matrices](https://lectures.quantecon.org/jl/julia_arrays.html)
- [ ] [Types, Methods, and Dispatch](https://lectures.quantecon.org/jl/types_methods.html)
- [ ] [The Need for Speed](https://lectures.quantecon.org/jl/need_for_speed.html)
- [ ] [Plotting in Julia](https://lectures.quantecon.org/jl/julia_plots.html)
- [ ] [Useful Libraries](https://lectures.quantecon.org/jl/julia_libraries.html)

## Tools and Techniques 
- [ ] [Linear Algebra](https://lectures.quantecon.org/jl/linear_algebra.html)
- [ ] [Orthogonal Projections and their Applications](https://lectures.quantecon.org/jl/orth_proj.html)
- [ ] [LLN and CLT](https://lectures.quantecon.org/jl/lln_clt.html)
- [ ] [Linear State-Space Models](https://lectures.quantecon.org/jl/linear_models.html)
- [ ] [Finite Markov Chains](https://lectures.quantecon.org/jl/finite_markov.html)
- [ ] [Continuous State Markov Chains](https://lectures.quantecon.org/jl/stationary_densities.html)
- [ ] [A First Look at the Kalman Filter](https://lectures.quantecon.org/jl/kalman.html)

## Dynamic Programming 
- [ ] [Shortest Paths](https://lectures.quantecon.org/jl/short_path.html)
- [ ] [Job Search I: The McCall Search Model](https://lectures.quantecon.org/jl/mccall_model.html)
- [ ] [Job Search II: Search and Separation](https://lectures.quantecon.org/jl/mccall_model_with_separation.html)
- [ ] [A Problem that Stumped Milton Friedman](https://lectures.quantecon.org/jl/wald_friedman.html)
- [ ] [Job Search III: Search with Learning](https://lectures.quantecon.org/jl/odu.html)
- [ ] [Job Search IV: Modeling Career Choice](https://lectures.quantecon.org/jl/career.html)
- [ ] [Job Search V: On-the-Job Search](https://lectures.quantecon.org/jl/jv.html)
- [ ] [Optimal Growth I: The Stochastic Optimal Growth Model](https://lectures.quantecon.org/jl/optgrowth.html)
- [ ] [Optimal Growth II: Time Iteration](https://lectures.quantecon.org/jl/coleman_policy_iter.html)
- [ ] [Optimal Growth III: The Endogenous Grid Method](https://lectures.quantecon.org/jl/egm_policy_iter.html)
- [ ] [LQ Dynamic Programming Problems](https://lectures.quantecon.org/jl/lqcontrol.html)
- [ ] [Optimal Savings I: The Permanent Income Model](https://lectures.quantecon.org/jl/perm_income.html)
- [ ] [Optimal Savings II: LQ Techniques](https://lectures.quantecon.org/jl/perm_income_cons.html)
- [ ] [Consumption and Tax Smoothing with Complete and Incomplete Markets](https://lectures.quantecon.org/jl/smoothing.html)
- [ ] [Optimal Savings III: Occasionally Binding Constraints](https://lectures.quantecon.org/jl/ifp.html)
- [ ] [Robustness](https://lectures.quantecon.org/jl/robustness.html)
- [ ] [Discrete State Dynamic Programming](https://lectures.quantecon.org/jl/discrete_dp.html)

## Multiple Agent Models
- [ ] [Schelling's Segregation Model](https://lectures.quantecon.org/jl/schelling.html)
- [ ] [A Lake Model of Employment and Unemployment](https://lectures.quantecon.org/jl/lake_model.html)
- [ ] [Rational Expectations Equilibrium](https://lectures.quantecon.org/jl/rational_expectations.html)
- [ ] [Markov Perfect Equilibrium](https://lectures.quantecon.org/jl/markov_perf.html)
- [ ] [Asset Pricing I: Finite State Models](https://lectures.quantecon.org/jl/markov_asset.html)
- [ ] [Asset Pricing II: The Lucas Asset Pricing Model](https://lectures.quantecon.org/jl/lucas_model.html)
- [ ] [Asset Pricing III: Incomplete Markets](https://lectures.quantecon.org/jl/harrison_kreps.html)
- [ ] [Uncertainty Traps](https://lectures.quantecon.org/jl/uncertainty_traps.html)
- [ ] [The Aiyagari Model](https://lectures.quantecon.org/jl/aiyagari.html)
- [ ] [Default Risk and Income Fluctuations](https://lectures.quantecon.org/jl/arellano.html)
- [ ] [Globalization and Cycles](https://lectures.quantecon.org/jl/matsuyama.html)

## Time Series Models
- [ ] [Covariance Stationary Processes](https://lectures.quantecon.org/jl/arma.html)
- [ ] [Estimation of Spectra](https://lectures.quantecon.org/jl/estspec.html)
- [ ] [Additive Functionals](https://lectures.quantecon.org/jl/additive_functionals.html)
- [ ] [Multiplicative Functionals](https://lectures.quantecon.org/jl/multiplicative_functionals.html)
- [ ] [Classical Control with Linear Algebra](https://lectures.quantecon.org/jl/lu_tricks.html)
- [ ] [Classical Filtering with Linear Algebra](https://lectures.quantecon.org/jl/classical_filtering.html)

## Dynamic Programming Squared
- [ ] [Dynamic Stackelberg Problems](https://lectures.quantecon.org/jl/dyn_stack.html)
- [ ] [Optimal Taxation in an LQ Economy](https://lectures.quantecon.org/jl/lqramsey.html)
- [ ] [Optimal Taxation with State-Contingent Debt](https://lectures.quantecon.org/jl/opt_tax_recur.html)
- [ ] [Optimal Taxation without State-Contingent Debt](https://lectures.quantecon.org/jl/amss.html)

**Comment by arnavs** [comment]
Also: eliminate double transposes wherever they occur (such as in the Kalman filter lecture).

**Comment by jlperla** [comment]
Active template for checklists:

## Getting Started with Julia
- [ ] [Setting up your Julia Environment](https://lectures.quantecon.org/jl/getting_started.html)
- [ ] [An Introductory Example](https://lectures.quantecon.org/jl/julia_by_example.html)
- [ ] [Julia Essentials](https://lectures.quantecon.org/jl/julia_essentials.html) and more material
- [ ] [Fundamental Types](https://lectures.quantecon.org/jl/julia_arrays.html)  with more material
- [ ] [Introduction to Types and Generic Programming](https://lectures.quantecon.org/jl/types_methods.html)

## More Programming and Software Engineering Principles
- [ ] Generic Programming
- [ ] [The Need for Speed](https://lectures.quantecon.org/jl/need_for_speed.html)
- [ ] [Plotting in Julia](https://lectures.quantecon.org/jl/julia_plots.html)
- [ ] [Useful Libraries](https://lectures.quantecon.org/jl/julia_libraries.html)

## Tools and Techniques 
- [ ] [Linear Algebra](https://lectures.quantecon.org/jl/linear_algebra.html)
- [ ] [Orthogonal Projections and their Applications](https://lectures.quantecon.org/jl/orth_proj.html)
- [ ] [LLN and CLT](https://lectures.quantecon.org/jl/lln_clt.html)
- [ ] [Linear State-Space Models](https://lectures.quantecon.org/jl/linear_models.html)
- [ ] [Finite Markov Chains](https://lectures.quantecon.org/jl/finite_markov.html)
- [ ] [Continuous State Markov Chains](https://lectures.quantecon.org/jl/stationary_densities.html)
- [ ] [A First Look at the Kalman Filter](https://lectures.quantecon.org/jl/kalman.html)

## Dynamic Programming 
- [ ] [Shortest Paths](https://lectures.quantecon.org/jl/short_path.html)
- [ ] [Job Search I: The McCall Search Model](https://lectures.quantecon.org/jl/mccall_model.html)
- [ ] [Job Search II: Search and Separation](https://lectures.quantecon.org/jl/mccall_model_with_separation.html)
- [ ] [A Problem that Stumped Milton Friedman](https://lectures.quantecon.org/jl/wald_friedman.html)
- [ ] [Job Search III: Search with Learning](https://lectures.quantecon.org/jl/odu.html)
- [ ] [Job Search IV: Modeling Career Choice](https://lectures.quantecon.org/jl/career.html)
- [ ] [Job Search V: On-the-Job Search](https://lectures.quantecon.org/jl/jv.html)
- [ ] [Optimal Growth I: The Stochastic Optimal Growth Model](https://lectures.quantecon.org/jl/optgrowth.html)
- [ ] [Optimal Growth II: Time Iteration](https://lectures.quantecon.org/jl/coleman_policy_iter.html)
- [ ] [Optimal Growth III: The Endogenous Grid Method](https://lectures.quantecon.org/jl/egm_policy_iter.html)
- [ ] [LQ Dynamic Programming Problems](https://lectures.quantecon.org/jl/lqcontrol.html)
- [ ] [Optimal Savings I: The Permanent Income Model](https://lectures.quantecon.org/jl/perm_income.html)
- [ ] [Optimal Savings II: LQ Techniques](https://lectures.quantecon.org/jl/perm_income_cons.html)
- [ ] [Consumption and Tax Smoothing with Complete and Incomplete Markets](https://lectures.quantecon.org/jl/smoothing.html)
- [ ] [Optimal Savings III: Occasionally Binding Constraints](https://lectures.quantecon.org/jl/ifp.html)
- [ ] [Robustness](https://lectures.quantecon.org/jl/robustness.html)
- [ ] [Discrete State Dynamic Programming](https://lectures.quantecon.org/jl/discrete_dp.html)

## Multiple Agent Models
- [ ] [Schelling's Segregation Model](https://lectures.quantecon.org/jl/schelling.html)
- [ ] [A Lake Model of Employment and Unemployment](https://lectures.quantecon.org/jl/lake_model.html)
- [ ] [Rational Expectations Equilibrium](https://lectures.quantecon.org/jl/rational_expectations.html)
- [ ] [Markov Perfect Equilibrium](https://lectures.quantecon.org/jl/markov_perf.html)
- [ ] [Asset Pricing I: Finite State Models](https://lectures.quantecon.org/jl/markov_asset.html)
- [ ] [Asset Pricing II: The Lucas Asset Pricing Model](https://lectures.quantecon.org/jl/lucas_model.html)
- [ ] [Asset Pricing III: Incomplete Markets](https://lectures.quantecon.org/jl/harrison_kreps.html)
- [ ] [Uncertainty Traps](https://lectures.quantecon.org/jl/uncertainty_traps.html)
- [ ] [The Aiyagari Model](https://lectures.quantecon.org/jl/aiyagari.html)
- [ ] [Default Risk and Income Fluctuations](https://lectures.quantecon.org/jl/arellano.html)
- [ ] [Globalization and Cycles](https://lectures.quantecon.org/jl/matsuyama.html)

## Time Series Models
- [ ] [Covariance Stationary Processes](https://lectures.quantecon.org/jl/arma.html)
- [ ] [Estimation of Spectra](https://lectures.quantecon.org/jl/estspec.html)
- [ ] [Additive Functionals](https://lectures.quantecon.org/jl/additive_functionals.html)
- [ ] [Multiplicative Functionals](https://lectures.quantecon.org/jl/multiplicative_functionals.html)
- [ ] [Classical Control with Linear Algebra](https://lectures.quantecon.org/jl/lu_tricks.html)
- [ ] [Classical Filtering with Linear Algebra](https://lectures.quantecon.org/jl/classical_filtering.html)

## Dynamic Programming Squared
- [ ] [Dynamic Stackelberg Problems](https://lectures.quantecon.org/jl/dyn_stack.html)
- [ ] [Optimal Taxation in an LQ Economy](https://lectures.quantecon.org/jl/lqramsey.html)
- [ ] [Optimal Taxation with State-Contingent Debt](https://lectures.quantecon.org/jl/opt_tax_recur.html)
- [ ] [Optimal Taxation without State-Contingent Debt](https://lectures.quantecon.org/jl/amss.html)
