### ISSUE TITLE
PyPlot and Gadfly to Plots

### ISSUE THREAD

**Issue by Nosferican** [QuantEcon/lecture-source-jl#67]
Every plot should use the `Plots.jl` API with the GR backend. In case of a plot not being able to be generated with the Plots API (bring the special case to attention for discussion).

- [ ] [Job Search IV: Modeling Career Choice](https://lectures.quantecon.org/jl/career.html)
- [x] [Optimal Growth I: The Stochastic Optimal Growth Model](https://lectures.quantecon.org/jl/optgrowth.html) (#84)
- [x] [Optimal Growth III: The Endogenous Grid Method](https://lectures.quantecon.org/jl/egm_policy_iter.html) (#95)
- [x] [Optimal Savings II: LQ Techniques](https://lectures.quantecon.org/jl/perm_income_cons.html) (#104)
- [x] [Consumption and Tax Smoothing with Complete and Incomplete Markets](https://lectures.quantecon.org/jl/smoothing.html) (#97)
- [x] [A Lake Model of Employment and Unemployment](https://lectures.quantecon.org/jl/lake_model.html) (#103)
- [x] [Rational Expectations Equilibrium](https://lectures.quantecon.org/jl/rational_expectations.html)
- [x] [Markov Perfect Equilibrium](https://lectures.quantecon.org/jl/markov_perf.html) (#102)
- [x] [Uncertainty Traps](https://lectures.quantecon.org/jl/uncertainty_traps.html)
- [x] [Default Risk and Income Fluctuations](https://lectures.quantecon.org/jl/arellano.html) (Gadfly|priority)
- [x] [Globalization and Cycles](https://lectures.quantecon.org/jl/matsuyama.html)
- [x] [Covariance Stationary Processes](https://lectures.quantecon.org/jl/arma.html) (#126)
- [x] [Estimation of Spectra](https://lectures.quantecon.org/jl/estspec.html)
- [x] [Additive Functionals](https://lectures.quantecon.org/jl/additive_functionals.html)
- [x] [Multiplicative Functionals](https://lectures.quantecon.org/jl/multiplicative_functionals.html)
- [x] [Classical Control with Linear Algebra](https://lectures.quantecon.org/jl/lu_tricks.html) (#122)
- [x] [Optimal Taxation in an LQ Economy](https://lectures.quantecon.org/jl/lqramsey.html) (#120)
- [x] [Optimal Taxation with State-Contingent Debt](https://lectures.quantecon.org/jl/opt_tax_recur.html) 
- [x] [Lucas Model] #163 
- [x] [Optimal Growth II: Time Iteration]

**Comment by arnavs** [comment]
As discussed, this is a good first issue for @ajozefiak. After you're done getting up to speed, maybe give this a go, and ping me if there are any issues.

**Comment by arnavs** [comment]
Until Adam joins the repo, I'll self-assign these just to keep track and remind myself to stay apprised of their status.

**Comment by ajozefiak** [comment]
I've gotten stuck with the surface plot in "Job Search IV: Modeling Career Choice". I am not sure if Plots has enough 'control' over the surface plot as compared to using GR or PyPlot directly.  

I've also gotten stuck on the last snippet of code in the Globalization and Cycles lecture. I've pushed a new branch matsuyama_plots where all of the plots except for the last one have been converted to the Plots API. Specifically, the last plot is an interactive plot and perhaps someone else knows how to work with this better than me.

**Comment by jlperla** [comment]
@ajozefiak Thanks so much on that.  We can review it next week.  If we need to drop some of the features, it may be worth it for reproducibility of setups.

**Comment by arnavs** [comment]
Handling these last two plots after discussion with @ajozefiak.
